name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (or other environment setup if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}  # 使用 secret
        run: |
          # 這裡添加你部署網站的命令
          echo "Deploying with API key..."
          # 如果你有部署腳本，這裡可以用到 API_KEY
          npm install -g gh-pages
          gh-pages -d build -r https://github.com/Ching-code/openweather_ajax_practice.git
